/* This file was generated by `qmk generate-config-h`. Do not edit or copy. */

#pragma once

#ifndef DEBOUNCE
#   define DEBOUNCE 5
#endif // DEBOUNCE

#ifndef DEVICE_VER
#   define DEVICE_VER 0x0001
#endif // DEVICE_VER

#ifndef DESCRIPTION
#   define DESCRIPTION bm40hsrgb
#endif // DESCRIPTION

#ifndef DIODE_DIRECTION
#   define DIODE_DIRECTION COL2ROW
#endif // DIODE_DIRECTION

#ifndef MANUFACTURER
#   define MANUFACTURER KPRepublic
#endif // MANUFACTURER

#ifndef RGB_DI_PIN
#   define RGB_DI_PIN E2
#endif // RGB_DI_PIN

#ifndef PRODUCT
#   define PRODUCT bm40hsrgb
#endif // PRODUCT

#ifndef PRODUCT_ID
#   define PRODUCT_ID 0x3430
#endif // PRODUCT_ID

#ifndef VENDOR_ID
#   define VENDOR_ID 0x4B50
#endif // VENDOR_ID

#ifndef MATRIX_COLS
#   define MATRIX_COLS 12
#endif // MATRIX_COLS

#ifndef MATRIX_COL_PINS
#   define MATRIX_COL_PINS { B6, C6, B4, D7, D4, D6, C7, F6, F5, F4, F1, F0 }
#endif // MATRIX_COL_PINS


#ifndef MATRIX_ROWS
#   define MATRIX_ROWS 4
#endif // MATRIX_ROWS

#ifndef MATRIX_ROW_PINS
#   define MATRIX_ROW_PINS { B3, B2, E6, B5 }
#endif // MATRIX_ROW_PINS
