# This file was generated by `qmk generate-rules-mk`. Do not edit or copy.

BOOTLOADER ?= atmel-dfu
LAYOUTS ?= ['planck_mit']
MCU ?= atmega32u4
MOUSEKEY_ENABLE ?= yes
EXTRAKEY_ENABLE ?= yes
CONSOLE_ENABLE ?= no
COMMAND_ENABLE ?= no
SLEEP_LED_ENABLE ?= no
NKRO_ENABLE ?= no
BACKLIGHT_ENABLE ?= no
BLUETOOTH_ENABLE ?= no
AUDIO_ENABLE ?= no
RGB_MATRIX_ENABLE ?= yes
BOOTMAGIC_ENABLE ?= lite
